[package]
name = "prima_uccisione"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "1.18"
borsh = "1.5.1"
borsh-derive = "1.5.1"
thiserror = "1.0"

# [[bin]]
# name = "prima_uccisione"
# path = "src/lib.rs"
