[package]
name = "beg"
version = "0.1.0"
edition = "2021"

# [dependencies]
# solana-sdk = "1.18"
# tokio = { version = "1", features = ["full"] }
# solana-client = "1.18"
# anyhow = "1.0"

[[bin]]
name = "BURHANKHAJA_"
path = "src/main.rs"
